project:
  type: website
  output-dir: docs

website:
  title: "Elaine Tsai"
  navbar:
    background: light
    left:
      - text: Home
        href: index.qmd
      - text: About
        href: about.qmd
      - text: Projects
        href: projects.qmd
      - text: Notes
        href: notes.qmd
  page-footer: "Copyright 2024, Elaine Tsai"

format:
  html:
    theme: flatly
    css: styles.css
    toc: false
