project:
  type: website
  output-dir: docs

website:
  title: "Elaine Tsai Ballinger"
  navbar:
    background: light
    left:
      - text: Home
        href: index.qmd
      - text: About
        href: about.qmd
      - text: Writing
        href: writing.qmd
      - text: Projects
        href: projects.qmd
  page-footer: "Copyright 2024, Elaine Ballinger"

format:
  html:
    theme: flatly
    css: styles.css
    toc: false
