project:
  type: website
  output-dir: docs
  resources:
    - CNAME

website:
  navbar:
    background: light
    left:
      - text: About
        href: index.qmd
      - text: Projects
        href: projects.qmd
      - text: Notes
        href: notes.qmd
  page-footer: "<i class=\"bi bi-pen\"></i> Elaine Tsai"

format:
  html:
    theme: flatly
    css: styles.css
    toc: false
